spring:
  application:
    name: article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videoblog-article?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.10.170:8848
        username: nacos
        password: nacos
mybatis:
  config-location: classpath:/db/mybatis-config.xml