spring:
  application:
    name: article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videoblog-article?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.10.170:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:10000
      datasource:
        ds1:
          nacos:
            server-addr: 47.106.10.170:8848
            dataId: article-service-flow-rules
            groupId: DEFAULT_GROUP
            ruleType: flow
            username: nacos
            password: nacos
mybatis:
  config-location: classpath:/db/mybatis-config.xml

logging:
  level:
    root: debug

feign:
  client:
    config:
      default:
        loggerLevel: HEADERS
  sentinel:
    enabled: true

#对所有信息对外暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'


app:
  secretKey: 1234567890asdasdasdasdasdadsa